name: Github-Pipeline

on:
    push:
        branches:
            - dev
            - qa
            - uat
            - sit
            - st
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set Up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'  
                  extensions: mbstring, xml, curl, zip

            - name: Install Composer Dependencies
              run: composer install

            - name: Build Docker Image
              run: docker build -t childguard360 .

            - name: Run Tests
              run: php artisan test
